#!/usr/bin/env bash

echo "Commit message hook"

if ! head -1 "$1" | grep -qE "^(feat|fix|ci|chore|docs|test|style|refactor)(\(.+?\))?: .{1,}$"; then
    echo "Aborting commit. Your commit message is invalid. (https://www.conventionalcommits.org/en/v1.0.0/#specification)" >&2
    exit 1
fi

if ! head -1 "$1" | grep -qE "^.{1,75}$"; then
    echo "Aborting commit. Your commit message is too long." >&2
    exit 1
fi