#!/usr/bin/env bash

echo "Pre-commit hook (golint)"

## this will retrieve all of the .go files that have been
## changed since the last commit
STAGED_GO_FILES=$(git diff --cached --name-only -- '*.go')

## we can check to see if this is empty
if [[ $STAGED_GO_FILES == "" ]]; then
  echo "No Updated Go Files"
# otherwise we can do stuff with these changed go files
else
  if ! golangci-lint run; then
    exit 1
  fi
fi
