#!/usr/bin/env bash

echo "Pre-push hook (test & build)"

## this will retrieve all of the .go files that have been
## changed since the last commit
STAGED_GO_FILES=$(git diff --cached --name-only -- '*.go')

## we can check to see if this is empty
if [[ $STAGED_GO_FILES == "" ]]; then
  echo "No Updated Go Files"
## otherwise we can do stuff with these changed go files
else
  echo "Test"
  go test -race -v -covermode=atomic ./...

  echo "Build"
  go build -o app

  rm app
fi
