version: '3.8'

services:
  pg-stats-api:
    container_name: pg-stats-api
    build: ./
    entrypoint: './pg-stats-api'
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      MIN_QUERY_DURATION: ${MIN_QUERY_DURATION}
      PG_HOST: ${PG_HOST}
      PG_PORT: ${PG_PORT}
      PG_USER: ${PG_USER}
      PG_PASSWORD: ${PG_PASSWORD}
      PG_DATABASE: ${PG_DATABASE}