openapi: 3.0.2
info:
  title: pg-stats-api
  description: Every operation may return a **500 Internal Server Error** response.
  version: 1.0.0

paths:
  /queries:
    get:
      summary: "Get queries"
      parameters:
        - in: query
          name: type
          schema: { type: string, enum: [ "SELECT","INSERT","DELETE","UPDATE" ] }
          required: false
        - in: query
          name: time_spent_sort
          schema: { type: string, enum: [ "asc","desc" ] }
          required: false
        - $ref: "#/components/parameters/PagingLimit"
        - $ref: "#/components/parameters/PagingPage"
      responses:
        200:
          description: ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  pagination: { $ref: '#/components/schemas/Pagination' }
                  payload:
                    type: array
                    items: { $ref: '#/components/schemas/Query' }
        400: { $ref: '#/components/responses/BadRequest' }


components:
  parameters:
    PagingLimit:
      name: limit
      in: query
      required: false
      schema: { type: integer }

    PagingPage:
      name: page
      in: query
      required: false
      schema: { type: integer }

  schemas:
    Query:
      type: object
      properties:
        id: { type: integer }
        statement: { type: string }
        max_exec_time: { type: number }
        mean_exec_time: { type: number }

    Pagination:
      type: object
      required: [ page, page_size ]
      properties:
        page: { type: integer }
        page_size: { type: integer }

    ErrorResponse:
      type: object
      required: [ code, message ,field ]
      properties:
        code: { type: integer }
        message: { type: string }
        field: { type: string }
      example:
        code: 400
        message: "Invalid parameter 'some_param'"
        field: "some_param"


  responses:
    BadRequest:
      description: Bad Request. The response message will contain further hints.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
